package GameLogic;

// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-11-28 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 11:53:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.List;
import java.util.HashSet;
import java.util.Iterator;
import java.util.ArrayList;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Token;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class external_Stratego {

// ***** VDMTOOLS START Name=parent KEEP=NO
  Stratego parent = null;
// ***** VDMTOOLS END Name=parent


// ***** VDMTOOLS START Name=external_Stratego#1|Stratego KEEP=NO
  public external_Stratego (Stratego parentStratego) {
    parent = parentStratego;
  }
// ***** VDMTOOLS END Name=external_Stratego#1|Stratego


// ***** VDMTOOLS START Name=external_Stratego KEEP=NO
  public external_Stratego () {}
// ***** VDMTOOLS END Name=external_Stratego


// ***** VDMTOOLS START Name=impl_updateTurn KEEP=NO
  public void impl_updateTurn () throws CGException {
    UTIL.RunTime("Preliminary Operation updateTurn has been called");
  }
// ***** VDMTOOLS END Name=impl_updateTurn


// ***** VDMTOOLS START Name=impl_isGameOver KEEP=NO
  public void impl_isGameOver () throws CGException {
    UTIL.RunTime("Preliminary Operation isGameOver has been called");
  }
// ***** VDMTOOLS END Name=impl_isGameOver

}
;
