//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-12-03 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Thu 14-Mar-2013 12:36:47 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\Miguel\\Dropbox\\projects\\stratego\\Stratego/Stratego.vdmpp".

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.Set;
import java.util.List;
import java.util.HashSet;
import java.util.Iterator;
import java.util.ArrayList;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Token;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Stratego implements EvaluatePP {


// ***** VDMTOOLS START Name=PieceConf KEEP=NO
  public static class PieceConf implements Record {

    public String name;

    public Number rank;

    public Number quantity;


    public PieceConf () {}


    public PieceConf (String p1, Number p2, Number p3) {
      name = p1;
      rank = p2;
      quantity = p3;
    }


    public Object clone () {
      return new PieceConf(name, rank, quantity);
    }


    public String toString () {
      return "mk_Stratego`PieceConf(" + UTIL.toString(name) + ", " + UTIL.toString(rank) + ", " + UTIL.toString(quantity) + ")";
    }


    public boolean equals (Object obj) {
      if (!(obj instanceof PieceConf)) 
        return false;
      else {
        PieceConf temp = (PieceConf)obj;
        return UTIL.equals(name, temp.name) && UTIL.equals(rank, temp.rank) && UTIL.equals(quantity, temp.quantity);
      }
    }


    public int hashCode () {
      return (name == null ? 0 : name.hashCode()) + (rank == null ? 0 : rank.hashCode()) + (quantity == null ? 0 : quantity.hashCode());
    }

  }
// ***** VDMTOOLS END Name=PieceConf
;

// ***** VDMTOOLS START Name=defaultPieces KEEP=NO
  private volatile List defaultPieces = null;
// ***** VDMTOOLS END Name=defaultPieces

// ***** VDMTOOLS START Name=playerOne KEEP=NO
  private volatile Player playerOne = null;
// ***** VDMTOOLS END Name=playerOne

// ***** VDMTOOLS START Name=playerTwo KEEP=NO
  private volatile Player playerTwo = null;
// ***** VDMTOOLS END Name=playerTwo

// ***** VDMTOOLS START Name=board KEEP=NO
  private volatile Board board = null;
// ***** VDMTOOLS END Name=board

// ***** VDMTOOLS START Name=currentPlayer KEEP=NO
  private volatile Player currentPlayer = null;
// ***** VDMTOOLS END Name=currentPlayer

// ***** VDMTOOLS START Name=gameIsOver KEEP=NO
  private volatile Boolean gameIsOver = null;
// ***** VDMTOOLS END Name=gameIsOver

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=StrategoSentinel KEEP=NO
  class StrategoSentinel extends Sentinel {

    public final int Stratego = 0;

    public final int gameOver = 1;

    public final int getBoard = 2;

    public final int initGame = 3;

    public final int makeMove = 4;

    public final int givePieces = 5;

    public final int isGameOver = 6;

    public final int makeBattle = 7;

    public final int updateTurn = 8;

    public final int moveIsValid = 9;

    public final int getPlayerOne = 10;

    public final int getPlayerTwo = 11;

    public final int givePiecesP1 = 12;

    public final int givePiecesP2 = 13;

    public final int hasValidMoves = 14;

    public final int makeBattleAux = 15;

    public final int getCurrentPlayer = 16;

    public final int placeInitialPieces = 17;

    public final int addDeadPieceToEnemy = 18;

    public final int countPiecesWithRank = 19;

    public final int middlePositionsAreFree = 20;

    public final int initPieceConfigurations = 21;

    public final int nr_functions = 22;


    public StrategoSentinel () throws CGException {}


    public StrategoSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=StrategoSentinel
;

// ***** VDMTOOLS START Name=evaluatePP#1|int KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return Boolean.TRUE;
  }
// ***** VDMTOOLS END Name=evaluatePP#1|int


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new StrategoSentinel(this);
    }
    catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=vdm_init_Stratego KEEP=NO
  private void vdm_init_Stratego () {
    try {
      setSentinel();
      defaultPieces = new ArrayList();
    }
    catch (Exception e) {
      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=vdm_init_Stratego


// ***** VDMTOOLS START Name=Stratego KEEP=NO
  public Stratego () throws CGException {
    try {
      vdm_init_Stratego();
      board = new Board();
      playerOne = new Player(new String("P1"), new quotes.Blue());
      playerTwo = new Player(new String("P2"), new quotes.Red());
      gameIsOver = Boolean.FALSE;
      currentPlayer = (Player)UTIL.clone(playerOne);
      initGame();
      setSentinel();
    }
    catch (Throwable e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Stratego


// ***** VDMTOOLS START Name=initGame KEEP=NO
  public void initGame () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).initGame);
    try {
      if (!this.pre_initGame().booleanValue()) 
        UTIL.RunTime("Precondition failure in initGame");
      initPieceConfigurations();
      givePiecesP1();
      givePiecesP2();
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).initGame);
    }
  }
// ***** VDMTOOLS END Name=initGame


// ***** VDMTOOLS START Name=pre_initGame KEEP=NO
  public Boolean pre_initGame () throws CGException {
    Boolean varRes_1 = null;
    Boolean var1_2 = null;
    if ((var1_2 = Boolean.valueOf(UTIL.equals(defaultPieces, new ArrayList()))).booleanValue()) 
      var1_2 = Boolean.valueOf(UTIL.equals(playerOne.getPieces(), new ArrayList()));
    if ((varRes_1 = var1_2).booleanValue()) 
      varRes_1 = Boolean.valueOf(UTIL.equals(playerTwo.getPieces(), new ArrayList()));
    return varRes_1;
  }
// ***** VDMTOOLS END Name=pre_initGame


// ***** VDMTOOLS START Name=initPieceConfigurations KEEP=NO
  private void initPieceConfigurations () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).initPieceConfigurations);
    try {
      if (!this.pre_initPieceConfigurations().booleanValue()) 
        UTIL.RunTime("Precondition failure in initPieceConfigurations");
      List tmpSeq_2 = new ArrayList();
      tmpSeq_2.add(new PieceConf(new String("FLAG"), new Integer(0), new Double(1)));
      tmpSeq_2.add(new PieceConf(new String("SPY"), new Integer(1), new Double(1)));
      tmpSeq_2.add(new PieceConf(new String("SCOUT"), new Integer(2), new Double(8)));
      tmpSeq_2.add(new PieceConf(new String("MINER"), new Integer(3), new Double(5)));
      tmpSeq_2.add(new PieceConf(new String("SERGEANT"), new Integer(4), new Double(4)));
      tmpSeq_2.add(new PieceConf(new String("LIUTENANT"), new Integer(5), new Double(4)));
      tmpSeq_2.add(new PieceConf(new String("CAPTAIN"), new Integer(6), new Double(4)));
      tmpSeq_2.add(new PieceConf(new String("MAJOR"), new Integer(7), new Double(3)));
      tmpSeq_2.add(new PieceConf(new String("COLONEL"), new Integer(8), new Double(2)));
      tmpSeq_2.add(new PieceConf(new String("GENERAL"), new Integer(9), new Double(1)));
      tmpSeq_2.add(new PieceConf(new String("MARSHAL"), new Integer(10), new Double(1)));
      tmpSeq_2.add(new PieceConf(new String("BOMB"), new Integer(11), new Double(6)));
      defaultPieces = UTIL.ConvertToList(UTIL.clone(tmpSeq_2));
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).initPieceConfigurations);
    }
  }
// ***** VDMTOOLS END Name=initPieceConfigurations


// ***** VDMTOOLS START Name=pre_initPieceConfigurations KEEP=NO
  private Boolean pre_initPieceConfigurations () throws CGException {
    return Boolean.valueOf(UTIL.equals(defaultPieces, new ArrayList()));
  }
// ***** VDMTOOLS END Name=pre_initPieceConfigurations


// ***** VDMTOOLS START Name=givePiecesP1 KEEP=NO
  public void givePiecesP1 () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).givePiecesP1);
    try {
      if (!this.pre_givePiecesP1().booleanValue()) 
        UTIL.RunTime("Precondition failure in givePiecesP1");
      givePieces(new quotes.Blue(), playerOne);
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).givePiecesP1);
    }
  }
// ***** VDMTOOLS END Name=givePiecesP1


// ***** VDMTOOLS START Name=pre_givePiecesP1 KEEP=NO
  public Boolean pre_givePiecesP1 () throws CGException {
    return Boolean.valueOf(UTIL.equals(playerOne.getPieces(), new ArrayList()));
  }
// ***** VDMTOOLS END Name=pre_givePiecesP1


// ***** VDMTOOLS START Name=givePiecesP2 KEEP=NO
  public void givePiecesP2 () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).givePiecesP2);
    try {
      if (!this.pre_givePiecesP2().booleanValue()) 
        UTIL.RunTime("Precondition failure in givePiecesP2");
      givePieces(new quotes.Red(), playerTwo);
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).givePiecesP2);
    }
  }
// ***** VDMTOOLS END Name=givePiecesP2


// ***** VDMTOOLS START Name=pre_givePiecesP2 KEEP=NO
  public Boolean pre_givePiecesP2 () throws CGException {
    return Boolean.valueOf(UTIL.equals(playerTwo.getPieces(), new ArrayList()));
  }
// ***** VDMTOOLS END Name=pre_givePiecesP2


// ***** VDMTOOLS START Name=givePieces#2|Object|Player KEEP=NO
  private void givePieces (final Object color, final Player player) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).givePieces);
    try {
      if (!this.pre_givePieces(color, player).booleanValue()) 
        UTIL.RunTime("Precondition failure in givePieces");
      {
        Set iset_7 = new HashSet(defaultPieces);
        Set tmpSet_29 = new HashSet(iset_7);
        for (Iterator enm_28 = tmpSet_29.iterator(); enm_28.hasNext(); ) {
          PieceConf elem_3 = (PieceConf)enm_28.next();
          PieceConf pieceConf = null;
          /* pieceConf */
          pieceConf = elem_3;
          {
            Set iset_10 = new HashSet();
            iset_10 = new HashSet();
            Number ub_17 = (pieceConf.quantity);
            if (!UTIL.IsInteger(ub_17)) 
              UTIL.RunTime("Upper bound was not an integer in set range expression");
            int ubi_16 = UTIL.NumberToInt(ub_17).intValue();
            for (int count_14 = 1; count_14 <= ubi_16; count_14++) 
              iset_10.add(new Integer(count_14));
            Set iset_18 = iset_10;
            Set tmpSet_27 = new HashSet(iset_18);
            for (Iterator enm_26 = tmpSet_27.iterator(); enm_26.hasNext(); ) {
              Number elem_8 = UTIL.NumberToInt(enm_26.next());
              Number i = null;
              /* i */
              i = elem_8;
              Number arg_21 = null;
              arg_21 = pieceConf.rank;
              String arg_23 = null;
              arg_23 = pieceConf.name;
              player.addPiece(new Piece(arg_21, color, arg_23));
            }
          }
        }
      }
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).givePieces);
    }
  }
// ***** VDMTOOLS END Name=givePieces#2|Object|Player


// ***** VDMTOOLS START Name=pre_givePieces#2|Object|Player KEEP=NO
  private Boolean pre_givePieces (final Object color, final Player player) throws CGException {
    Boolean varRes_3 = null;
    Boolean var1_4 = null;
    Set var2_7 = new HashSet();
    var2_7.add(new quotes.Blue());
    var2_7.add(new quotes.Red());
    if ((var1_4 = Boolean.valueOf(UTIL.Contains(var2_7, color))).booleanValue()) 
      var1_4 = Boolean.valueOf(UTIL.equals(player, playerOne));
    if (!(varRes_3 = var1_4).booleanValue()) 
      varRes_3 = Boolean.valueOf(UTIL.equals(player, playerTwo));
    return varRes_3;
  }
// ***** VDMTOOLS END Name=pre_givePieces#2|Object|Player


// ***** VDMTOOLS START Name=countPiecesWithRank#2|List|Number KEEP=NO
  private Number countPiecesWithRank (final List pieces, final Number rank) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).countPiecesWithRank);
    try {
      if (!this.pre_countPiecesWithRank(pieces, rank).booleanValue()) 
        UTIL.RunTime("Precondition failure in countPiecesWithRank");
      {
        Number counter = null;
        counter = new Integer(0);
        {
          Set iset_8 = new HashSet(pieces);
          Set tmpSet_16 = new HashSet(iset_8);
          for (Iterator enm_15 = tmpSet_16.iterator(); enm_15.hasNext(); ) {
            Piece elem_4 = (Piece)enm_15.next();
            Piece piece = null;
            /* piece */
            piece = elem_4;
            if (piece.getRank().intValue() == rank.intValue()) 
              counter = new Integer(counter.intValue() + 1);
          }
        }
        return counter;
      }
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).countPiecesWithRank);
    }
  }
// ***** VDMTOOLS END Name=countPiecesWithRank#2|List|Number


// ***** VDMTOOLS START Name=pre_countPiecesWithRank#2|List|Number KEEP=NO
  private Boolean pre_countPiecesWithRank (final List pieces, final Number rank) throws CGException {
    Boolean varRes_3 = null;
    Set var2_6 = new HashSet();
    var2_6 = new HashSet();
    for (int count_9 = 0; count_9 <= 11; count_9++) 
      var2_6.add(new Integer(count_9));
    if ((varRes_3 = Boolean.valueOf(UTIL.Contains(var2_6, rank))).booleanValue()) 
      varRes_3 = Boolean.valueOf(!(pieces.size() == 0));
    return varRes_3;
  }
// ***** VDMTOOLS END Name=pre_countPiecesWithRank#2|List|Number


// ***** VDMTOOLS START Name=placeInitialPieces KEEP=NO
  public void placeInitialPieces () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).placeInitialPieces);
    try {
      if (!this.pre_placeInitialPieces().booleanValue()) 
        UTIL.RunTime("Precondition failure in placeInitialPieces");
      board.placePiecesP1(playerOne.getPieces());
      playerOne.removePieces();
      board.placePiecesP2(playerTwo.getPieces());
      playerTwo.removePieces();
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).placeInitialPieces);
    }
  }
// ***** VDMTOOLS END Name=placeInitialPieces


// ***** VDMTOOLS START Name=pre_placeInitialPieces KEEP=NO
  public Boolean pre_placeInitialPieces () throws CGException {
    Boolean varRes_1 = null;
    Boolean var1_2 = null;
    if ((var1_2 = Boolean.valueOf(board.getNumberPiecesOnBoard().intValue() == 0)).booleanValue()) 
      var1_2 = Boolean.valueOf(!UTIL.equals(playerOne.getPieces(), new ArrayList()));
    if ((varRes_1 = var1_2).booleanValue()) 
      varRes_1 = Boolean.valueOf(!UTIL.equals(playerTwo.getPieces(), new ArrayList()));
    return varRes_1;
  }
// ***** VDMTOOLS END Name=pre_placeInitialPieces


// ***** VDMTOOLS START Name=getPlayerOne KEEP=NO
  public Player getPlayerOne () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).getPlayerOne);
    try {
      return playerOne;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).getPlayerOne);
    }
  }
// ***** VDMTOOLS END Name=getPlayerOne


// ***** VDMTOOLS START Name=getPlayerTwo KEEP=NO
  public Player getPlayerTwo () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).getPlayerTwo);
    try {
      return playerTwo;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).getPlayerTwo);
    }
  }
// ***** VDMTOOLS END Name=getPlayerTwo


// ***** VDMTOOLS START Name=getCurrentPlayer KEEP=NO
  public Player getCurrentPlayer () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).getCurrentPlayer);
    try {
      return currentPlayer;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).getCurrentPlayer);
    }
  }
// ***** VDMTOOLS END Name=getCurrentPlayer


// ***** VDMTOOLS START Name=getBoard KEEP=NO
  public Board getBoard () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).getBoard);
    try {
      return board;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).getBoard);
    }
  }
// ***** VDMTOOLS END Name=getBoard


// ***** VDMTOOLS START Name=makeMove#2|Coord|Coord KEEP=NO
  public Number makeMove (final Coord srcPos, final Coord destPos) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).makeMove);
    try {
      Piece srcPiece = null;
      Piece destPiece = null;
      Number result = null;
      Boolean cond_3 = null;
      if (!(cond_3 = board.isPositionFree(srcPos)).booleanValue()) 
        cond_3 = board.isPositionLake(srcPos);
      if (cond_3.booleanValue()) 
        return new Integer(1);
      Object rhs_11 = board.getPieceAtPosition(srcPos);
      if (!(rhs_11 instanceof Piece)) 
        UTIL.RunTime("Incompatible type");
      srcPiece = (Piece)UTIL.clone(rhs_11);
      if (!UTIL.equals(srcPiece.getColor(), currentPlayer.getColor())) 
        return new Integer(2);
      else {
        if (board.isPositionLake(destPos).booleanValue()) 
          return new Integer(3);
      }
      if (!board.isPositionFree(destPos).booleanValue()) {
        Object rhs_24 = board.getPieceAtPosition(destPos);
        if (!(rhs_24 instanceof Piece)) 
          UTIL.RunTime("Incompatible type");
        destPiece = (Piece)UTIL.clone(rhs_24);
        if (UTIL.equals(destPiece.getColor(), currentPlayer.getColor())) 
          return new Integer(4);
      }
      result = UTIL.NumberToInt(UTIL.clone(moveIsValid(srcPos, destPos, srcPiece)));
      if (result.intValue() == 0) {
        if (board.isPositionFree(destPos).booleanValue()) {
          board.movePiece(srcPos, destPos);
          return result;
        }
        else {
          makeBattle(srcPos, destPos, srcPiece, destPiece);
          return new Integer(0);
        }
      }
      else 
        return result;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).makeMove);
    }
  }
// ***** VDMTOOLS END Name=makeMove#2|Coord|Coord


// ***** VDMTOOLS START Name=makeBattle#4|Coord|Coord|Piece|Piece KEEP=NO
  private void makeBattle (final Coord srcPos, final Coord destPos, final Piece srcPiece, final Piece destPiece) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).makeBattle);
    try {
      if (!this.pre_makeBattle(srcPos, destPos, srcPiece, destPiece).booleanValue()) 
        UTIL.RunTime("Precondition failure in makeBattle");
      Boolean cond_5 = null;
      Boolean var1_6 = null;
      if ((var1_6 = Boolean.valueOf(UTIL.equals(srcPiece.getName(), new String("MINER")))).booleanValue()) 
        var1_6 = Boolean.valueOf(UTIL.equals(destPiece.getName(), new String("BOMB")));
      if (!(cond_5 = var1_6).booleanValue()) {
        Boolean var2_13 = null;
        if ((var2_13 = Boolean.valueOf(UTIL.equals(srcPiece.getName(), new String("SPY")))).booleanValue()) 
          var2_13 = Boolean.valueOf(UTIL.equals(destPiece.getName(), new String("MARSHAL")));
        cond_5 = var2_13;
      }
      if (cond_5.booleanValue()) {
        Piece obj_69 = board.getPieceAtPosition(srcPos);
        obj_69.wasSpoted();
        makeBattleAux(srcPos, destPos, destPiece, board.getNumberPiecesOnBoard());
      }
      else {
        if (srcPiece.getRank().intValue() == destPiece.getRank().intValue()) {
          board.removePiece(srcPos);
          board.removePiece(destPos);
          currentPlayer.addDeadPiece(srcPiece);
          addDeadPieceToEnemy(destPiece);
        }
        else {
          Boolean cond_34 = null;
          if ((cond_34 = Boolean.valueOf(srcPiece.getRank().intValue() > destPiece.getRank().intValue())).booleanValue()) 
            cond_34 = Boolean.valueOf(!UTIL.equals(destPiece.getName(), new String("FLAG")));
          if (cond_34.booleanValue()) {
            Piece obj_44 = board.getPieceAtPosition(srcPos);
            obj_44.wasSpoted();
            makeBattleAux(srcPos, destPos, destPiece, board.getNumberPiecesOnBoard());
          }
          else {
            if (srcPiece.getRank().intValue() < destPiece.getRank().intValue()) {
              board.removePiece(srcPos);
              currentPlayer.addDeadPiece(srcPiece);
              Piece obj_33 = board.getPieceAtPosition(destPos);
              obj_33.wasSpoted();
            }
          }
        }
        if (UTIL.equals(destPiece.getName(), new String("FLAG"))) {
          Piece obj_64 = board.getPieceAtPosition(destPos);
          obj_64.wasSpoted();
          gameOver();
        }
      }
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).makeBattle);
    }
  }
// ***** VDMTOOLS END Name=makeBattle#4|Coord|Coord|Piece|Piece


// ***** VDMTOOLS START Name=pre_makeBattle#4|Coord|Coord|Piece|Piece KEEP=NO
  private Boolean pre_makeBattle (final Coord srcPos, final Coord destPos, final Piece srcPiece, final Piece destPiece) throws CGException {
    return Boolean.valueOf(!UTIL.equals(srcPiece.getColor(), destPiece.getColor()));
  }
// ***** VDMTOOLS END Name=pre_makeBattle#4|Coord|Coord|Piece|Piece


// ***** VDMTOOLS START Name=makeBattleAux#4|Coord|Coord|Piece|Number KEEP=NO
  private void makeBattleAux (final Coord srcPos, final Coord destPos, final Piece destPiece, final Number numberPieces) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).makeBattleAux);
    try {
      if (!this.pre_makeBattleAux(srcPos, destPos, destPiece, numberPieces).booleanValue()) 
        UTIL.RunTime("Precondition failure in makeBattleAux");
      board.removePiece(destPos);
      board.movePiece(srcPos, destPos);
      addDeadPieceToEnemy(destPiece);
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).makeBattleAux);
    }
  }
// ***** VDMTOOLS END Name=makeBattleAux#4|Coord|Coord|Piece|Number


// ***** VDMTOOLS START Name=pre_makeBattleAux#4|Coord|Coord|Piece|Number KEEP=NO
  private Boolean pre_makeBattleAux (final Coord srcPos, final Coord destPos, final Piece destPiece, final Number numberPieces) throws CGException {
    Piece obj_9 = board.getPieceAtPosition(srcPos);
    return Boolean.valueOf(!UTIL.equals(obj_9.getColor(), destPiece.getColor()));
  }
// ***** VDMTOOLS END Name=pre_makeBattleAux#4|Coord|Coord|Piece|Number


// ***** VDMTOOLS START Name=addDeadPieceToEnemy#1|Piece KEEP=NO
  private void addDeadPieceToEnemy (final Piece piece) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).addDeadPieceToEnemy);
    try {
      if (UTIL.equals(currentPlayer, playerOne)) 
        playerTwo.addDeadPiece(piece);
      else 
        playerOne.addDeadPiece(piece);
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).addDeadPieceToEnemy);
    }
  }
// ***** VDMTOOLS END Name=addDeadPieceToEnemy#1|Piece


// ***** VDMTOOLS START Name=moveIsValid#3|Coord|Coord|Piece KEEP=NO
  public Number moveIsValid (final Coord srcPos, final Coord destPos, final Piece srcPiece) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).moveIsValid);
    try {
      if (!this.pre_moveIsValid(srcPos, destPos, srcPiece).booleanValue()) 
        UTIL.RunTime("Precondition failure in moveIsValid");
      Boolean cond_4 = null;
      if ((cond_4 = Boolean.valueOf(!(srcPos.getX().intValue() == destPos.getX().intValue()))).booleanValue()) 
        cond_4 = Boolean.valueOf(!(srcPos.getY().intValue() == destPos.getY().intValue()));
      if (cond_4.booleanValue()) 
        return new Integer(11);
      Set var2_14 = new HashSet();
      var2_14.add(new String("FLAG"));
      var2_14.add(new String("BOMB"));
      if (UTIL.Contains(var2_14, srcPiece.getName())) 
        return new Integer(12);
      else if (UTIL.equals(srcPiece.getName(), new String("SCOUT"))) {
        if (middlePositionsAreFree(srcPos, destPos).booleanValue()) 
          return new Integer(0);
        else 
          return new Integer(14);
      }
      else {
        Boolean cond_17 = null;
        if (!(cond_17 = Boolean.valueOf(Math.abs((destPos.getX().intValue() - srcPos.getX().intValue())) == 1)).booleanValue()) 
          cond_17 = Boolean.valueOf(Math.abs((destPos.getY().intValue() - srcPos.getY().intValue())) == 1);
        if (cond_17.booleanValue()) 
          return new Integer(0);
        else 
          return new Integer(13);
      }
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).moveIsValid);
    }
  }
// ***** VDMTOOLS END Name=moveIsValid#3|Coord|Coord|Piece


// ***** VDMTOOLS START Name=pre_moveIsValid#3|Coord|Coord|Piece KEEP=NO
  public Boolean pre_moveIsValid (final Coord srcPos, final Coord destPos, final Piece srcPiece) throws CGException {
    return Boolean.valueOf(!Coord.areEqual(srcPos, destPos).booleanValue());
  }
// ***** VDMTOOLS END Name=pre_moveIsValid#3|Coord|Coord|Piece


// ***** VDMTOOLS START Name=middlePositionsAreFree#2|Coord|Coord KEEP=NO
  public Boolean middlePositionsAreFree (final Coord srcPos, final Coord destPos) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).middlePositionsAreFree);
    try {
      if (!this.pre_middlePositionsAreFree(srcPos, destPos).booleanValue()) 
        UTIL.RunTime("Precondition failure in middlePositionsAreFree");
      {
        List positions = null;
        if (srcPos.getY().intValue() > destPos.getY().intValue()) {
          List tmpSeq_52 = new ArrayList();
          for (int count_53 = (destPos.getY().intValue() + 1); count_53 <= (srcPos.getY().intValue() - 1); count_53++) {
            Number y = new Integer(count_53);
            Number arg_61 = null;
            arg_61 = srcPos.getX();
            tmpSeq_52.add(new Coord(arg_61, y));
          }
          positions = UTIL.ConvertToList(UTIL.clone(tmpSeq_52));
        }
        else if (srcPos.getY().intValue() < destPos.getY().intValue()) {
          List tmpSeq_40 = new ArrayList();
          for (int count_41 = (srcPos.getY().intValue() + 1); count_41 <= (destPos.getY().intValue() - 1); count_41++) {
            Number y = new Integer(count_41);
            Number arg_49 = null;
            arg_49 = srcPos.getX();
            tmpSeq_40.add(new Coord(arg_49, y));
          }
          positions = UTIL.ConvertToList(UTIL.clone(tmpSeq_40));
        }
        else {
          if (srcPos.getX().intValue() > destPos.getX().intValue()) {
            List tmpSeq_25 = new ArrayList();
            for (int count_26 = (destPos.getX().intValue() + 1); count_26 <= (srcPos.getX().intValue() - 1); count_26++) {
              Number x = new Integer(count_26);
              Number arg_35 = null;
              arg_35 = srcPos.getY();
              tmpSeq_25.add(new Coord(x, arg_35));
            }
            positions = UTIL.ConvertToList(UTIL.clone(tmpSeq_25));
          }
          else {
            if (srcPos.getX().intValue() < destPos.getX().intValue()) {
              List tmpSeq_10 = new ArrayList();
              for (int count_11 = (srcPos.getX().intValue() + 1); count_11 <= (destPos.getX().intValue() - 1); count_11++) {
                Number x = new Integer(count_11);
                Number arg_20 = null;
                arg_20 = srcPos.getY();
                tmpSeq_10.add(new Coord(x, arg_20));
              }
              positions = UTIL.ConvertToList(UTIL.clone(tmpSeq_10));
            }
          }
        }
        {
          Set iset_67 = new HashSet(positions);
          Set tmpSet_73 = new HashSet(iset_67);
          for (Iterator enm_72 = tmpSet_73.iterator(); enm_72.hasNext(); ) {
            Coord elem_63 = (Coord)enm_72.next();
            Coord position = null;
            /* position */
            position = elem_63;
            if (!board.isPositionFree(position).booleanValue()) 
              return Boolean.FALSE;
          }
        }
        return Boolean.TRUE;
      }
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).middlePositionsAreFree);
    }
  }
// ***** VDMTOOLS END Name=middlePositionsAreFree#2|Coord|Coord


// ***** VDMTOOLS START Name=pre_middlePositionsAreFree#2|Coord|Coord KEEP=NO
  public Boolean pre_middlePositionsAreFree (final Coord srcPos, final Coord destPos) throws CGException {
    return Boolean.valueOf(!Coord.areEqual(srcPos, destPos).booleanValue());
  }
// ***** VDMTOOLS END Name=pre_middlePositionsAreFree#2|Coord|Coord


// ***** VDMTOOLS START Name=hasValidMoves#1|Player KEEP=NO
  public Boolean hasValidMoves (final Player player) throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).hasValidMoves);
    try {
      List surroundingPos = null;
      Coord coord = null;
      Piece piece = null;
      {
        Set iset_4 = new HashSet();
        iset_4 = new HashSet();
        int ubi_9 = Board.BOARDSIZE.intValue();
        for (int count_7 = 1; count_7 <= ubi_9; count_7++) 
          iset_4.add(new Integer(count_7));
        Set iset_10 = iset_4;
        Set tmpSet_130 = new HashSet(iset_10);
        for (Iterator enm_129 = tmpSet_130.iterator(); enm_129.hasNext(); ) {
          Number elem_2 = UTIL.NumberToInt(enm_129.next());
          Number i = null;
          /* i */
          i = elem_2;
          {
            Set iset_13 = new HashSet();
            iset_13 = new HashSet();
            int ubi_18 = Board.BOARDSIZE.intValue();
            for (int count_16 = 1; count_16 <= ubi_18; count_16++) 
              iset_13.add(new Integer(count_16));
            Set iset_19 = iset_13;
            Set tmpSet_128 = new HashSet(iset_19);
            for (Iterator enm_127 = tmpSet_128.iterator(); enm_127.hasNext(); ) {
              Number elem_11 = UTIL.NumberToInt(enm_127.next());
              Number j = null;
              /* j */
              j = elem_11;
              coord = new Coord(j, i);
              piece = (Piece)UTIL.clone(board.getPieceAtPosition(coord));
              Boolean cond_25 = null;
              if ((cond_25 = Boolean.valueOf(!UTIL.equals(piece, null))).booleanValue()) 
                cond_25 = Boolean.valueOf(UTIL.equals(piece.getColor(), player.getColor()));
              if (cond_25.booleanValue()) {
                List rhs_33 = new ArrayList();
                if (!(((Object)rhs_33) instanceof List)) 
                  UTIL.RunTime("Incompatible type");
                surroundingPos = UTIL.ConvertToList(UTIL.clone(rhs_33));
                List rhs_34 = null;
                List tmpSeq_37 = new ArrayList();
                List tmpSeq_39 = new ArrayList();
                tmpSeq_39.add(new Integer(i.intValue() - 1));
                tmpSeq_39.add(j);
                tmpSeq_37.add(tmpSeq_39);
                List tmpSeq_45 = new ArrayList();
                tmpSeq_45.add(i);
                tmpSeq_45.add(new Integer(j.intValue() - 1));
                tmpSeq_37.add(tmpSeq_45);
                List tmpSeq_51 = new ArrayList();
                tmpSeq_51.add(new Integer(i.intValue() + 1));
                tmpSeq_51.add(j);
                tmpSeq_37.add(tmpSeq_51);
                List tmpSeq_57 = new ArrayList();
                tmpSeq_57.add(i);
                tmpSeq_57.add(new Integer(j.intValue() + 1));
                tmpSeq_37.add(tmpSeq_57);
                rhs_34 = new ArrayList(surroundingPos);
                rhs_34.addAll(tmpSeq_37);
                List rhs_62 = rhs_34;
                if (!(((Object)rhs_62) instanceof List)) 
                  UTIL.RunTime("Incompatible type");
                surroundingPos = UTIL.ConvertToList(UTIL.clone(rhs_62));
                {
                  Set iset_67 = new HashSet(surroundingPos);
                  Set tmpSet_126 = new HashSet(iset_67);
                  for (Iterator enm_125 = tmpSet_126.iterator(); enm_125.hasNext(); ) {
                    List elem_63 = UTIL.ConvertToList(enm_125.next());
                    List possiblePos = null;
                    /* possiblePos */
                    possiblePos = elem_63;
                    Boolean cond_68 = null;
                    Boolean var1_69 = null;
                    Boolean var1_70 = null;
                    if ((1 > 1) || (1 > possiblePos.size())) 
                      UTIL.RunTime("Illegal index");
                    if ((var1_70 = Boolean.valueOf(UTIL.NumberToInt(possiblePos.get(0)).intValue() >= 1)).booleanValue()) {
                      if ((1 > 1) || (1 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      var1_70 = Boolean.valueOf(UTIL.NumberToInt(possiblePos.get(0)).intValue() <= Board.BOARDSIZE.intValue());
                    }
                    if ((var1_69 = var1_70).booleanValue()) {
                      if ((1 > 2) || (2 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      var1_69 = Boolean.valueOf(UTIL.NumberToInt(possiblePos.get(1)).intValue() >= 1);
                    }
                    if ((cond_68 = var1_69).booleanValue()) {
                      if ((1 > 2) || (2 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      cond_68 = Boolean.valueOf(UTIL.NumberToInt(possiblePos.get(1)).intValue() <= Board.BOARDSIZE.intValue());
                    }
                    if (cond_68.booleanValue()) {
                      Number arg_93 = null;
                      if ((1 > 2) || (2 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      arg_93 = UTIL.NumberToInt(possiblePos.get(1));
                      Number arg_94 = null;
                      if ((1 > 1) || (1 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      arg_94 = UTIL.NumberToInt(possiblePos.get(0));
                      piece = (Piece)UTIL.clone(board.getPieceAtPosition(new Coord(arg_93, arg_94)));
                      Boolean cond_99 = null;
                      Number arg_106 = null;
                      if ((1 > 2) || (2 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      arg_106 = UTIL.NumberToInt(possiblePos.get(1));
                      Number arg_107 = null;
                      if ((1 > 1) || (1 > possiblePos.size())) 
                        UTIL.RunTime("Illegal index");
                      arg_107 = UTIL.NumberToInt(possiblePos.get(0));
                      if ((cond_99 = Boolean.valueOf(moveIsValid(new Coord(j, i), new Coord(arg_106, arg_107), (Piece)board.getPieceAtPosition(new Coord(j, i))).intValue() == 0)).booleanValue()) {
                        Boolean var2_117 = null;
                        if (!(var2_117 = Boolean.valueOf(UTIL.equals(piece, null))).booleanValue()) 
                          var2_117 = Boolean.valueOf(!UTIL.equals(piece.getColor(), player.getColor()));
                        cond_99 = var2_117;
                      }
                      if (cond_99.booleanValue()) 
                        return Boolean.TRUE;
                    }
                  }
                }
              }
            }
          }
        }
      }
      return Boolean.FALSE;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).hasValidMoves);
    }
  }
// ***** VDMTOOLS END Name=hasValidMoves#1|Player


// ***** VDMTOOLS START Name=updateTurn KEEP=NO
  public void updateTurn () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).updateTurn);
    try {
      if (UTIL.equals(currentPlayer, playerOne)) 
        currentPlayer = (Player)UTIL.clone(playerTwo);
      else 
        currentPlayer = (Player)UTIL.clone(playerOne);
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).updateTurn);
    }
  }
// ***** VDMTOOLS END Name=updateTurn


// ***** VDMTOOLS START Name=gameOver KEEP=NO
  private void gameOver () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).gameOver);
    try {
      if (!this.pre_gameOver().booleanValue()) 
        UTIL.RunTime("Precondition failure in gameOver");
      gameIsOver = Boolean.TRUE;
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).gameOver);
    }
  }
// ***** VDMTOOLS END Name=gameOver


// ***** VDMTOOLS START Name=pre_gameOver KEEP=NO
  private Boolean pre_gameOver () throws CGException {
    return Boolean.valueOf(UTIL.equals(gameIsOver, Boolean.FALSE));
  }
// ***** VDMTOOLS END Name=pre_gameOver


// ***** VDMTOOLS START Name=isGameOver KEEP=NO
  public Boolean isGameOver () throws CGException {
    sentinel.entering(((StrategoSentinel)sentinel).isGameOver);
    try {
      if (gameIsOver.booleanValue()) 
        return gameIsOver;
      else if (!UTIL.equals(currentPlayer.getPieces(), new ArrayList())) 
        return gameIsOver;
      else {
        if (UTIL.equals(currentPlayer, playerOne)) 
          gameIsOver = (Boolean)UTIL.clone(Boolean.valueOf(!hasValidMoves(playerTwo).booleanValue()));
        else 
          gameIsOver = (Boolean)UTIL.clone(Boolean.valueOf(!hasValidMoves(playerOne).booleanValue()));
        return gameIsOver;
      }
    }
    finally {
      sentinel.leaving(((StrategoSentinel)sentinel).isGameOver);
    }
  }
// ***** VDMTOOLS END Name=isGameOver

}
;
